### ISSUE TITLE
Badge isn't generated without 'master' branch

### ISSUE THREAD

**Issue by yanBrandao** [vbrandl/hoc#100]
I had delete master branch and add added HoC badge to my readme and he didnt show up, and after talked with Valetin by email, the solution was create a master branch.

**Comment by vbrandl** [comment]
I investigated the issue today but didn't find a quick solution to this issue.

In 6896a22 I implemented graceful error handling if there is no `master` branch. It will return a 404 with a descriptive error message instead of an internal server error:


![img-2020-02-12-205617](https://user-images.githubusercontent.com/20639051/74372192-881c8080-4dda-11ea-9e36-98c85b32db8b.png)

**Comment by yanBrandao** [comment]
Thank you for the reply, I solved my problem creating a master branch, but every time that I need to update HOC numbers. I had to make a pull request to master.

**Comment by vbrandl** [comment]
@yanBrandao I implemented support for custom branches in c9a54eda493912db422a53e2f840428ddd0d4a65 and will deploy it soon, so if you'd like to request badges for other branches, you can do so now by passing `?branch=<branch-name>` to any endpoint.
